_format_version: "3.0"
_transform: true

services:
  - name: orders
    url: http://host.docker.internal:3333
    protocol: http
    host: host.docker.internal
    port: 3333
    path: /orders
    routes:
      - name: api
        protocols:
          - http
          - https
        paths:
          - /orders

services:
  - name: invoices
    url: http://host.docker.internal:3334
    protocol: http
    host: host.docker.internal
    port: 3334
    path: /invoices
    routes:
      - name: api
        protocols:
          - http
          - https
        paths:
          - /invoices

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization